Run signing job
Signed-off-by: Peter Engelbert <pmengelbert@gmail.com>

diff --git a/pipeline.yml b/pipeline.yml
--- a/pipeline.yml
+++ b/pipeline.yml
@@ -102,7 +102,7 @@ stages:
                 echo "##vso[task.setvariable variable=spec.pattern;isoutput=true]$spec_pattern"
               name: buildPackage
               displayName: Build package
-              env: 
+              env:
                 SPEC_FILE: "$(bundle.dir)/${{ spec.distro }}/$(pkg.os)_${{ replace(spec.arch, '/', '') }}/${{ spec.package }}-${{ spec.distro }}-${{ replace(spec.arch, '/', '') }}-spec.json"
             - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
               displayName: Generate SBOM
@@ -121,16 +121,15 @@ stages:
                   ${{ spec.distro }}_\
                   ${{ replace(spec.arch, '/', '') }}_\
                   ${{ replace(spec.tag, '.', '_') }}"
-          # dependsOn: 
-          #   - "Build_\
-          #         ${{ replace(spec.package, '-', '_') }}_\
-          #         ${{ spec.distro }}_\
-          #         ${{ replace(spec.arch, '/', '') }}_\
-          #         ${{ replace(spec.tag, '.', '_') }}"
+          dependsOn:
+            - "Build_\
+                  ${{ replace(spec.package, '-', '_') }}_\
+                  ${{ spec.distro }}_\
+                  ${{ replace(spec.arch, '/', '') }}_\
+                  ${{ replace(spec.tag, '.', '_') }}"
           condition: ne('${{ spec.distro }}', 'windows')
           pool: $(build.pool)
           variables:
-            stage.id: 
             bundle.dir: "$(Pipeline.Workspace)/bundles"
             artifact.pattern: "$[ stageDependencies.Build.Build_\
                                  ${{ replace(spec.package, '-', '_') }}_\
@@ -222,82 +221,82 @@ stages:
             inputs:
               pathToPublish: "$(Pipeline.Workspace)/signed"
               artifactName: signed
-      - job: Upload_Packages
-        dependsOn: ["Sign_Packages"]
-        pool: production-pool-amd64-mariner-2
-        steps:
-          - download: current
-            artifact: signed
-          - bash: |
-              set -euo pipefail
+      # - job: Upload_Packages
+      #   dependsOn: ["Sign_Packages"]
+      #   pool: production-pool-amd64-mariner-2
+      #   steps:
+      #     - download: current
+      #       artifact: signed
+      #     - bash: |
+      #         set -euo pipefail
 
-              # uploads signed files to prod bucket, removes unsigned / failed uploads, writes output to stdout
-              go run ./cmd/pop upload \
-                --signed-dir="$SIGNED_DIR" \
-                --messages-file="${MSG_DIR}/downloaded" |
-                tee "${MSG_DIR}/succeeded"
-            env:
-              SIGNED_DIR: "$(Pipeline.Workspace)/signed"
-              MSG_DIR: "$(Pipeline.Workspace)/messages"
-            displayName: Upload Signed Packages to Prod Storage
-            name: uploadPackages
-          - bash: |
-              readarray -t failed < <(jq -r '.[] | .content | @base64d | fromjson.artifact.name' < "${MSG_DIR}/failed_singing_or_publishing")
-              for f in "${failed[@]}"; do
-                printf '##vso[task.logissue type=error;]failed signing or uploading:  %s\n' "$f"
-              done
-            env:
-              MSG_DIR: "$(Pipeline.Workspace)/messages"
-            displayName: Surface failed uploads
-      - job: Update_Latest
-        dependsOn: ["Sign_Packages", "Upload_Packages"]
-        pool: production-pool-amd64-mariner-2
-        steps:
-          - checkout: self
-          - bash: az login --identity
-            displayName: Login to Azure
-          - bash: scripts/generate-versions.sh
-            displayName: Generate versions
-            env:
-              AZURE_STORAGE_ACCOUNT: ${{ parameters.prod_storage_account_name }}
-              STORAGE_CONTAINER: moby
-              OUTPUT: $(Build.ArtifactStagingDirectory)
-          - task: PublishBuildArtifacts@1
-            displayName: Store pipeline artifacts
-            inputs:
-              artifactName: versions
-          - bash: |
-              set -ex
+      #         # uploads signed files to prod bucket, removes unsigned / failed uploads, writes output to stdout
+      #         go run ./cmd/pop upload \
+      #           --signed-dir="$SIGNED_DIR" \
+      #           --messages-file="${MSG_DIR}/downloaded" |
+      #           tee "${MSG_DIR}/succeeded"
+      #       env:
+      #         SIGNED_DIR: "$(Pipeline.Workspace)/signed"
+      #         MSG_DIR: "$(Pipeline.Workspace)/messages"
+      #       displayName: Upload Signed Packages to Prod Storage
+      #       name: uploadPackages
+      #     - bash: |
+      #         readarray -t failed < <(jq -r '.[] | .content | @base64d | fromjson.artifact.name' < "${MSG_DIR}/failed_singing_or_publishing")
+      #         for f in "${failed[@]}"; do
+      #           printf '##vso[task.logissue type=error;]failed signing or uploading:  %s\n' "$f"
+      #         done
+      #       env:
+      #         MSG_DIR: "$(Pipeline.Workspace)/messages"
+      #       displayName: Surface failed uploads
+      # - job: Update_Latest
+      #   dependsOn: ["Sign_Packages", "Upload_Packages"]
+      #   pool: production-pool-amd64-mariner-2
+      #   steps:
+      #     - checkout: self
+      #     - bash: az login --identity
+      #       displayName: Login to Azure
+      #     - bash: scripts/generate-versions.sh
+      #       displayName: Generate versions
+      #       env:
+      #         AZURE_STORAGE_ACCOUNT: ${{ parameters.prod_storage_account_name }}
+      #         STORAGE_CONTAINER: moby
+      #         OUTPUT: $(Build.ArtifactStagingDirectory)
+      #     - task: PublishBuildArtifacts@1
+      #       displayName: Store pipeline artifacts
+      #       inputs:
+      #         artifactName: versions
+      #     - bash: |
+      #         set -ex
 
-              az storage container create -n "${STORAGE_CONTAINER}" --auth-mode=login --public-access=blob
+      #         az storage container create -n "${STORAGE_CONTAINER}" --auth-mode=login --public-access=blob
 
-              az storage blob upload-batch \
-                --max-connections=10 --auth-mode=login \
-                --overwrite \
-                --source "${BUILD_ARTIFACTSTAGINGDIRECTORY}/" \
-                --destination "${STORAGE_CONTAINER}" \
-                --destination-path "/" \
-                --pattern "*.json" \
-                --content-type "application/json"
+      #         az storage blob upload-batch \
+      #           --max-connections=10 --auth-mode=login \
+      #           --overwrite \
+      #           --source "${BUILD_ARTIFACTSTAGINGDIRECTORY}/" \
+      #           --destination "${STORAGE_CONTAINER}" \
+      #           --destination-path "/" \
+      #           --pattern "*.json" \
+      #           --content-type "application/json"
 
-              az storage blob upload-batch \
-                --max-connections=10 --auth-mode=login \
-                --overwrite \
-                --source "${BUILD_ARTIFACTSTAGINGDIRECTORY}/" \
-                --destination "${STORAGE_CONTAINER}" \
-                --destination-path "/" \
-                --pattern "*.rss" \
-                --content-type "application/rss+xml"
+      #         az storage blob upload-batch \
+      #           --max-connections=10 --auth-mode=login \
+      #           --overwrite \
+      #           --source "${BUILD_ARTIFACTSTAGINGDIRECTORY}/" \
+      #           --destination "${STORAGE_CONTAINER}" \
+      #           --destination-path "/" \
+      #           --pattern "*.rss" \
+      #           --content-type "application/rss+xml"
 
-              az storage blob upload-batch \
-                --max-connections=10 --auth-mode=login \
-                --overwrite \
-                --source "${BUILD_ARTIFACTSTAGINGDIRECTORY}/" \
-                --destination "${STORAGE_CONTAINER}" \
-                --destination-path "/" \
-                --pattern "**/latest/*" \
-                --content-type "text/plain"
-            displayName: Upload versions to blob storage
-            env:
-              AZURE_STORAGE_ACCOUNT: ${{ parameters.prod_storage_account_name }}
-              STORAGE_CONTAINER: ${{ parameters.index_container }}
+      #         az storage blob upload-batch \
+      #           --max-connections=10 --auth-mode=login \
+      #           --overwrite \
+      #           --source "${BUILD_ARTIFACTSTAGINGDIRECTORY}/" \
+      #           --destination "${STORAGE_CONTAINER}" \
+      #           --destination-path "/" \
+      #           --pattern "**/latest/*" \
+      #           --content-type "text/plain"
+      #       displayName: Upload versions to blob storage
+      #       env:
+      #         AZURE_STORAGE_ACCOUNT: ${{ parameters.prod_storage_account_name }}
+      #         STORAGE_CONTAINER: ${{ parameters.index_container }}
