Wait for file to be present
There appears to be a race condition, whereby the spec file from the
artifact store is not yet present when we need it.

Signed-off-by: Peter Engelbert <pmengelbert@gmail.com>

diff --git a/pipeline.yml b/pipeline.yml
--- a/pipeline.yml
+++ b/pipeline.yml
@@ -112,7 +112,7 @@ stages:
               inputs:
                 pathToPublish: "$(Pipeline.Workspace)/bundles"
                 artifactName: bundles
-  - stage: TestAndSBOM
+  - stage: Test
     dependsOn: ["Build"]
     jobs:
       - ${{ each spec in parameters.specs }}:
@@ -162,6 +162,21 @@ stages:
             - script: |
                 set -exu
 
+                timeout_in_seconds=15
+                secs=0
+                t1="$(date +%s)"
+
+                while ! [ -f "$SPEC_FILE" ]; do
+                  sleep 1
+                  t2="$(date +%s)"
+                  secs=$((t2-t1))
+
+                  if [ "$secs" -gt "$timeout_in_seconds" ]; then
+                    printf '##vso[task.logissue type=error;]file "%s" never found, exiting' "$SPEC_FILE"
+                    exit 1
+                  fi
+                done
+
                 # runs the tests
                 go run ./cmd/run_tests "$SPEC_FILE" "$BUNDLE_DIR"
               displayName: Integration Test
@@ -175,7 +190,7 @@ stages:
                 pathToPublish: "tests/.test"
                 artifactName: testresults
   - stage: SignAndPublish
-    dependsOn: ["TestAndSBOM"]
+    dependsOn: ["Test"]
     jobs:
       - job: Sign_Packages
         pool: production-pool-amd64-mariner-2
